import type { Contact, Company, Deal, Activity, CRMSettings } from '../types';

export const seedCompanies: Company[] = [
  {
    id: 'comp-1',
    name: 'TechCorp Solutions',
    industry: 'Technology',
    website: 'https://techcorp.example.com',
    size: 'medium',
    revenue: '$5M - $10M',
    address: '123 Tech Street, San Francisco, CA',
    status: 'customer',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'comp-2',
    name: 'Global Industries',
    industry: 'Manufacturing',
    website: 'https://globalind.example.com',
    size: 'enterprise',
    revenue: '$50M+',
    address: '456 Industrial Ave, Chicago, IL',
    status: 'customer',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'comp-3',
    name: 'StartupXYZ',
    industry: 'SaaS',
    website: 'https://startupxyz.example.com',
    size: 'startup',
    revenue: '$100K - $500K',
    address: '789 Innovation Blvd, Austin, TX',
    status: 'prospect',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'comp-4',
    name: 'RetailMax',
    industry: 'Retail',
    website: 'https://retailmax.example.com',
    size: 'medium',
    revenue: '$10M - $50M',
    address: '321 Commerce St, New York, NY',
    status: 'churned',
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const seedContacts: Contact[] = [
  {
    id: 'cont-1',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@techcorp.example.com',
    phone: '+1 (555) 123-4567',
    company: 'TechCorp Solutions',
    companyId: 'comp-1',
    title: 'VP of Engineering',
    status: 'active',
    tags: ['decision-maker', 'technical'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'cont-2',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'michael.chen@globalind.example.com',
    phone: '+1 (555) 234-5678',
    company: 'Global Industries',
    companyId: 'comp-2',
    title: 'CTO',
    status: 'active',
    tags: ['decision-maker', 'executive'],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'cont-3',
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily@startupxyz.example.com',
    phone: '+1 (555) 345-6789',
    company: 'StartupXYZ',
    companyId: 'comp-3',
    title: 'Founder & CEO',
    status: 'lead',
    tags: ['founder', 'decision-maker'],
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'cont-4',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'j.wilson@techcorp.example.com',
    phone: '+1 (555) 456-7890',
    company: 'TechCorp Solutions',
    companyId: 'comp-1',
    title: 'Senior Developer',
    status: 'active',
    tags: ['technical', 'champion'],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'cont-5',
    firstName: 'Lisa',
    lastName: 'Martinez',
    email: 'lisa.m@retailmax.example.com',
    phone: '+1 (555) 567-8901',
    company: 'RetailMax',
    companyId: 'comp-4',
    title: 'IT Director',
    status: 'inactive',
    tags: ['technical'],
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const seedDeals: Deal[] = [
  {
    id: 'deal-1',
    title: 'TechCorp Enterprise License',
    value: 75000,
    stage: 'negotiation',
    probability: 70,
    contactId: 'cont-1',
    companyId: 'comp-1',
    expectedCloseDate: new Date('2024-04-30'),
    notes: 'Final pricing discussion scheduled',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'deal-2',
    title: 'Global Industries Platform Upgrade',
    value: 150000,
    stage: 'proposal',
    probability: 50,
    contactId: 'cont-2',
    companyId: 'comp-2',
    expectedCloseDate: new Date('2024-05-15'),
    notes: 'Proposal sent, awaiting feedback',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'deal-3',
    title: 'StartupXYZ Starter Package',
    value: 12000,
    stage: 'qualified',
    probability: 30,
    contactId: 'cont-3',
    companyId: 'comp-3',
    expectedCloseDate: new Date('2024-06-01'),
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'deal-4',
    title: 'TechCorp Add-on Services',
    value: 25000,
    stage: 'closed_won',
    probability: 100,
    contactId: 'cont-4',
    companyId: 'comp-1',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'deal-5',
    title: 'RetailMax Annual Contract',
    value: 45000,
    stage: 'closed_lost',
    probability: 0,
    contactId: 'cont-5',
    companyId: 'comp-4',
    notes: 'Lost to competitor - price sensitivity',
    createdAt: new Date('2023-10-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const seedActivities: Activity[] = [
  {
    id: 'act-1',
    type: 'meeting',
    title: 'Product demo with Sarah',
    description: 'Demonstrate new features and pricing options',
    contactId: 'cont-1',
    dealId: 'deal-1',
    dueDate: new Date('2024-03-25'),
    completed: false,
    createdAt: new Date('2024-03-15'),
  },
  {
    id: 'act-2',
    type: 'call',
    title: 'Follow-up call with Michael',
    description: 'Discuss proposal feedback',
    contactId: 'cont-2',
    dealId: 'deal-2',
    dueDate: new Date('2024-03-20'),
    completed: true,
    createdAt: new Date('2024-03-10'),
  },
  {
    id: 'act-3',
    type: 'email',
    title: 'Send case study to Emily',
    description: 'Share relevant SaaS customer success stories',
    contactId: 'cont-3',
    dealId: 'deal-3',
    dueDate: new Date('2024-03-18'),
    completed: false,
    createdAt: new Date('2024-03-12'),
  },
  {
    id: 'act-4',
    type: 'task',
    title: 'Prepare contract for TechCorp',
    dealId: 'deal-1',
    dueDate: new Date('2024-03-28'),
    completed: false,
    createdAt: new Date('2024-03-15'),
  },
  {
    id: 'act-5',
    type: 'note',
    title: 'Competitor analysis update',
    description: 'RetailMax went with CompetitorX due to 20% lower pricing',
    companyId: 'comp-4',
    completed: true,
    createdAt: new Date('2024-01-05'),
  },
];

export const seedCRMSettings: CRMSettings = {
  companyName: 'Acme Corp',
  currency: 'USD',
  isSetupComplete: true,
};
