import type { Contact, Company, Deal, Activity, CRMSettings } from '../types';

const daysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date;
};

export const seedCompanies: Company[] = [
  {
    id: 'comp-1',
    name: 'Meridian Healthcare',
    industry: 'Healthcare',
    website: 'https://meridianhc.com',
    size: 'enterprise',
    revenue: '$50M+',
    address: '2200 Memorial Dr, Houston, TX 77030',
    status: 'customer',
    createdAt: daysAgo(340),
    updatedAt: daysAgo(12),
  },
  {
    id: 'comp-2',
    name: 'Korvus Logistics',
    industry: 'Logistics',
    website: 'https://korvus.io',
    size: 'medium',
    revenue: '$10M - $50M',
    address: '88 Harbor Blvd, Long Beach, CA',
    status: 'customer',
    createdAt: daysAgo(210),
    updatedAt: daysAgo(3),
  },
  {
    id: 'comp-3',
    name: 'Pinecone Studios',
    industry: 'Media & Entertainment',
    website: 'https://pineconestudios.co',
    size: 'small',
    revenue: '$1M - $5M',
    address: '415 NW Couch St, Portland, OR',
    status: 'customer',
    createdAt: daysAgo(180),
    updatedAt: daysAgo(45),
  },
  {
    id: 'comp-4',
    name: 'Vellum Financial',
    industry: 'Financial Services',
    website: 'https://vellumfin.com',
    size: 'enterprise',
    revenue: '$50M+',
    address: '1 State Street, 30th Floor, New York, NY',
    status: 'prospect',
    createdAt: daysAgo(28),
    updatedAt: daysAgo(5),
  },
  {
    id: 'comp-5',
    name: 'GreenLoop',
    industry: 'Sustainability',
    website: 'https://greenloop.earth',
    size: 'startup',
    revenue: '$500K - $1M',
    status: 'prospect',
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
  },
  {
    id: 'comp-6',
    name: 'Nomad Workspace',
    industry: 'Real Estate',
    website: 'https://nomadws.com',
    size: 'medium',
    revenue: '$5M - $10M',
    address: '120 Kearny St, San Francisco, CA',
    status: 'customer',
    createdAt: daysAgo(400),
    updatedAt: daysAgo(60),
  },
  {
    id: 'comp-7',
    name: 'Arclight Manufacturing',
    industry: 'Manufacturing',
    website: 'https://arclightmfg.com',
    size: 'medium',
    revenue: '$10M - $50M',
    address: '7400 Industrial Pkwy, Cleveland, OH',
    status: 'churned',
    createdAt: daysAgo(500),
    updatedAt: daysAgo(90),
  },
  {
    id: 'comp-8',
    name: 'Tidewater Insurance',
    industry: 'Insurance',
    website: 'https://tidewaterins.com',
    size: 'enterprise',
    revenue: '$50M+',
    address: '300 E Lombard St, Baltimore, MD',
    status: 'prospect',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    id: 'comp-9',
    name: 'BrightPath Education',
    industry: 'Education',
    size: 'small',
    revenue: '$1M - $5M',
    status: 'prospect',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: 'comp-10',
    name: 'Ridgeline Construction',
    industry: 'Construction',
    website: 'https://ridgelineco.com',
    size: 'medium',
    revenue: '$10M - $50M',
    address: '950 S Cherry St, Denver, CO',
    status: 'customer',
    createdAt: daysAgo(290),
    updatedAt: daysAgo(20),
  },
  {
    id: 'comp-11',
    name: 'Flux Creative',
    industry: 'Marketing',
    website: 'https://fluxcreative.co',
    size: 'small',
    revenue: '$500K - $1M',
    status: 'churned',
    createdAt: daysAgo(320),
    updatedAt: daysAgo(150),
  },
  {
    id: 'comp-12',
    name: 'Atlas Pharma',
    industry: 'Pharmaceuticals',
    website: 'https://atlaspharma.com',
    size: 'enterprise',
    revenue: '$50M+',
    address: '200 Park Ave, Florham Park, NJ',
    status: 'customer',
    createdAt: daysAgo(260),
    updatedAt: daysAgo(8),
  },
];

export const seedContacts: Contact[] = [
  {
    id: 'cont-1',
    firstName: 'Rachel',
    lastName: 'Thornton',
    email: 'r.thornton@meridianhc.com',
    phone: '+1 832-555-0147',
    company: 'Meridian Healthcare',
    companyId: 'comp-1',
    title: 'Director of Operations',
    status: 'active',
    tags: ['decision-maker', 'renewal-2025'],
    createdAt: daysAgo(340),
    updatedAt: daysAgo(12),
  },
  {
    id: 'cont-2',
    firstName: 'Derek',
    lastName: 'Osman',
    email: 'dosman@meridianhc.com',
    company: 'Meridian Healthcare',
    companyId: 'comp-1',
    title: 'IT Manager',
    status: 'active',
    tags: ['technical', 'champion'],
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
  },
  {
    id: 'cont-3',
    firstName: 'Nina',
    lastName: 'Kowalski',
    email: 'nina@korvus.io',
    phone: '+1 562-555-0234',
    company: 'Korvus Logistics',
    companyId: 'comp-2',
    title: 'COO',
    status: 'active',
    tags: ['decision-maker', 'executive'],
    createdAt: daysAgo(210),
    updatedAt: daysAgo(3),
  },
  {
    id: 'cont-4',
    firstName: 'Marcus',
    lastName: 'Webb',
    email: 'mwebb@korvus.io',
    phone: '+1 562-555-0299',
    company: 'Korvus Logistics',
    companyId: 'comp-2',
    title: 'Warehouse Director',
    status: 'active',
    tags: ['end-user'],
    createdAt: daysAgo(180),
    updatedAt: daysAgo(45),
  },
  {
    id: 'cont-5',
    firstName: 'Zoe',
    lastName: 'Park',
    email: 'zoe@pineconestudios.co',
    phone: '+1 503-555-0188',
    company: 'Pinecone Studios',
    companyId: 'comp-3',
    title: 'Head of Production',
    status: 'active',
    tags: ['decision-maker'],
    createdAt: daysAgo(180),
    updatedAt: daysAgo(45),
  },
  {
    id: 'cont-6',
    firstName: 'Jonathan',
    lastName: 'Hargrove',
    email: 'jhargrove@vellumfin.com',
    phone: '+1 212-555-0301',
    company: 'Vellum Financial',
    companyId: 'comp-4',
    title: 'VP Engineering',
    status: 'lead',
    tags: ['decision-maker', 'enterprise'],
    notes: 'Met at FinTech Summit. Very interested in automation use case.',
    createdAt: daysAgo(28),
    updatedAt: daysAgo(5),
  },
  {
    id: 'cont-7',
    firstName: 'Priya',
    lastName: 'Anand',
    email: 'priya@greenloop.earth',
    company: 'GreenLoop',
    companyId: 'comp-5',
    title: 'CEO & Co-founder',
    status: 'lead',
    tags: ['founder', 'decision-maker'],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
  },
  {
    id: 'cont-8',
    firstName: 'Tom',
    lastName: 'Brecker',
    email: 'tbrecker@nomadws.com',
    phone: '+1 415-555-0177',
    company: 'Nomad Workspace',
    companyId: 'comp-6',
    title: 'CTO',
    status: 'active',
    tags: ['technical', 'decision-maker'],
    createdAt: daysAgo(400),
    updatedAt: daysAgo(60),
  },
  {
    id: 'cont-9',
    firstName: 'Sandra',
    lastName: 'Liu',
    email: 's.liu@arclightmfg.com',
    phone: '+1 216-555-0422',
    company: 'Arclight Manufacturing',
    companyId: 'comp-7',
    title: 'Procurement Manager',
    status: 'inactive',
    tags: [],
    notes: 'Left the company in Jan. Need new contact.',
    createdAt: daysAgo(500),
    updatedAt: daysAgo(90),
  },
  {
    id: 'cont-10',
    firstName: 'David',
    lastName: 'Kessler',
    email: 'dkessler@tidewaterins.com',
    phone: '+1 410-555-0289',
    company: 'Tidewater Insurance',
    companyId: 'comp-8',
    title: 'Chief Digital Officer',
    status: 'lead',
    tags: ['executive', 'decision-maker'],
    notes: 'Inbound from website. Wants demo this week.',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    id: 'cont-11',
    firstName: 'Amy',
    lastName: 'Sato',
    email: 'amy.sato@brightpathedu.org',
    company: 'BrightPath Education',
    companyId: 'comp-9',
    title: 'Director of Technology',
    status: 'lead',
    tags: ['decision-maker'],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: 'cont-12',
    firstName: 'Carl',
    lastName: 'Johannsen',
    email: 'carl@ridgelineco.com',
    phone: '+1 720-555-0134',
    company: 'Ridgeline Construction',
    companyId: 'comp-10',
    title: 'VP of Technology',
    status: 'active',
    tags: ['decision-maker', 'technical'],
    createdAt: daysAgo(290),
    updatedAt: daysAgo(20),
  },
  {
    id: 'cont-13',
    firstName: 'Leila',
    lastName: 'Hassan',
    email: 'lhassan@ridgelineco.com',
    company: 'Ridgeline Construction',
    companyId: 'comp-10',
    title: 'Project Coordinator',
    status: 'active',
    tags: ['end-user', 'champion'],
    createdAt: daysAgo(250),
    updatedAt: daysAgo(20),
  },
  {
    id: 'cont-14',
    firstName: 'Greg',
    lastName: 'Morales',
    email: 'gmorales@atlaspharma.com',
    phone: '+1 973-555-0511',
    company: 'Atlas Pharma',
    companyId: 'comp-12',
    title: 'Head of Digital Transformation',
    status: 'active',
    tags: ['decision-maker', 'enterprise'],
    createdAt: daysAgo(260),
    updatedAt: daysAgo(8),
  },
  {
    id: 'cont-15',
    firstName: 'Natalie',
    lastName: 'Voss',
    email: 'nvoss@atlaspharma.com',
    company: 'Atlas Pharma',
    companyId: 'comp-12',
    title: 'QA Lead',
    status: 'active',
    tags: ['technical', 'end-user'],
    createdAt: daysAgo(200),
    updatedAt: daysAgo(30),
  },
  {
    id: 'cont-16',
    firstName: 'Kevin',
    lastName: 'Ng',
    email: 'kevin@vellumfin.com',
    company: 'Vellum Financial',
    companyId: 'comp-4',
    title: 'Senior Engineer',
    status: 'lead',
    tags: ['technical', 'evaluator'],
    createdAt: daysAgo(21),
    updatedAt: daysAgo(5),
  },
  {
    id: 'cont-17',
    firstName: 'Mia',
    lastName: 'Torres',
    email: 'mia.t@fluxcreative.co',
    company: 'Flux Creative',
    companyId: 'comp-11',
    title: 'Managing Director',
    status: 'inactive',
    tags: ['decision-maker'],
    notes: 'Churned Q3 last year. Budget cuts.',
    createdAt: daysAgo(320),
    updatedAt: daysAgo(150),
  },
];

export const seedDeals: Deal[] = [
  {
    id: 'deal-1',
    title: 'Meridian - Annual Renewal + Expansion',
    value: 120000,
    stage: 'negotiation',
    probability: 75,
    contactId: 'cont-1',
    companyId: 'comp-1',
    expectedCloseDate: daysAgo(-15),
    notes: 'Adding 3 new departments. Rachel wants volume discount. Need to loop in Derek for technical sign-off.',
    createdAt: daysAgo(60),
    updatedAt: daysAgo(3),
  },
  {
    id: 'deal-2',
    title: 'Korvus - Warehouse Module',
    value: 45000,
    stage: 'proposal',
    probability: 50,
    contactId: 'cont-3',
    companyId: 'comp-2',
    expectedCloseDate: daysAgo(-30),
    notes: 'Sent proposal last Tuesday. Nina said she needs board approval for anything over 40k.',
    createdAt: daysAgo(45),
    updatedAt: daysAgo(7),
  },
  {
    id: 'deal-3',
    title: 'Vellum Financial - Enterprise Platform',
    value: 250000,
    stage: 'qualified',
    probability: 25,
    contactId: 'cont-6',
    companyId: 'comp-4',
    expectedCloseDate: daysAgo(-60),
    notes: 'Big opportunity. Evaluating us vs. two competitors. Kevin is running the technical eval.',
    createdAt: daysAgo(28),
    updatedAt: daysAgo(5),
  },
  {
    id: 'deal-4',
    title: 'Tidewater - Claims Processing POC',
    value: 35000,
    stage: 'lead',
    probability: 10,
    contactId: 'cont-10',
    companyId: 'comp-8',
    expectedCloseDate: daysAgo(-45),
    notes: 'Inbound lead. David wants a quick POC for claims processing automation.',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    id: 'deal-5',
    title: 'GreenLoop - Starter Plan',
    value: 8000,
    stage: 'qualified',
    probability: 40,
    contactId: 'cont-7',
    companyId: 'comp-5',
    expectedCloseDate: daysAgo(-20),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(10),
  },
  {
    id: 'deal-6',
    title: 'Ridgeline - Phase 2 Rollout',
    value: 80000,
    stage: 'proposal',
    probability: 60,
    contactId: 'cont-12',
    companyId: 'comp-10',
    expectedCloseDate: daysAgo(-25),
    notes: 'Phase 1 went well. Carl is pushing for faster timeline. Leila confirmed field teams are ready.',
    createdAt: daysAgo(40),
    updatedAt: daysAgo(8),
  },
  {
    id: 'deal-7',
    title: 'Atlas Pharma - Compliance Add-on',
    value: 95000,
    stage: 'negotiation',
    probability: 80,
    contactId: 'cont-14',
    companyId: 'comp-12',
    expectedCloseDate: daysAgo(-10),
    notes: 'Legal is reviewing our DPA. Greg says almost done, just waiting on their counsel.',
    createdAt: daysAgo(90),
    updatedAt: daysAgo(4),
  },
  {
    id: 'deal-8',
    title: 'Pinecone - Team Upgrade',
    value: 18000,
    stage: 'closed_won',
    probability: 100,
    contactId: 'cont-5',
    companyId: 'comp-3',
    createdAt: daysAgo(60),
    updatedAt: daysAgo(22),
  },
  {
    id: 'deal-9',
    title: 'Nomad Workspace - Renewal',
    value: 36000,
    stage: 'closed_won',
    probability: 100,
    contactId: 'cont-8',
    companyId: 'comp-6',
    createdAt: daysAgo(75),
    updatedAt: daysAgo(45),
  },
  {
    id: 'deal-10',
    title: 'Arclight - Full Platform',
    value: 65000,
    stage: 'closed_lost',
    probability: 0,
    contactId: 'cont-9',
    companyId: 'comp-7',
    notes: 'Lost - went with in-house solution. Sandra left shortly after. Dead account.',
    createdAt: daysAgo(200),
    updatedAt: daysAgo(90),
  },
  {
    id: 'deal-11',
    title: 'Flux Creative - Annual',
    value: 12000,
    stage: 'closed_lost',
    probability: 0,
    contactId: 'cont-17',
    companyId: 'comp-11',
    notes: 'Churned. Budget cuts across the board. Mia said maybe next year.',
    createdAt: daysAgo(320),
    updatedAt: daysAgo(150),
  },
  {
    id: 'deal-12',
    title: 'BrightPath - Initial Pilot',
    value: 15000,
    stage: 'lead',
    probability: 10,
    contactId: 'cont-11',
    companyId: 'comp-9',
    expectedCloseDate: daysAgo(-50),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
];

export const seedActivities: Activity[] = [
  {
    id: 'act-1',
    type: 'meeting',
    title: 'Pricing review with Rachel',
    description: 'Go over volume discount structure for the expansion. Bring updated pricing sheet.',
    contactId: 'cont-1',
    dealId: 'deal-1',
    dueDate: daysAgo(-2),
    completed: false,
    createdAt: daysAgo(5),
  },
  {
    id: 'act-2',
    type: 'call',
    title: 'Follow up with Nina on proposal',
    description: 'Check if she got board approval yet',
    contactId: 'cont-3',
    dealId: 'deal-2',
    dueDate: daysAgo(-1),
    completed: false,
    createdAt: daysAgo(4),
  },
  {
    id: 'act-3',
    type: 'email',
    title: 'Send technical specs to Kevin',
    description: 'He asked for API docs and rate limits. Also SSO integration details.',
    contactId: 'cont-16',
    dealId: 'deal-3',
    dueDate: daysAgo(0),
    completed: false,
    createdAt: daysAgo(2),
  },
  {
    id: 'act-4',
    type: 'meeting',
    title: 'Demo for David Kessler',
    description: 'Claims processing walkthrough. 30 min. He mentioned their current tool is Guidewire.',
    contactId: 'cont-10',
    dealId: 'deal-4',
    dueDate: daysAgo(-3),
    completed: false,
    createdAt: daysAgo(5),
  },
  {
    id: 'act-5',
    type: 'task',
    title: 'Prepare SOW for Atlas compliance add-on',
    dealId: 'deal-7',
    dueDate: daysAgo(-1),
    completed: false,
    createdAt: daysAgo(4),
  },
  {
    id: 'act-6',
    type: 'call',
    title: 'Intro call with Amy Sato',
    description: 'BrightPath inbound. Interested in student records automation.',
    contactId: 'cont-11',
    dealId: 'deal-12',
    dueDate: daysAgo(-4),
    completed: false,
    createdAt: daysAgo(3),
  },
  {
    id: 'act-7',
    type: 'email',
    title: 'Send case study to Priya',
    description: 'She wanted to see sustainability-focused customer examples',
    contactId: 'cont-7',
    dealId: 'deal-5',
    dueDate: daysAgo(2),
    completed: true,
    createdAt: daysAgo(8),
  },
  {
    id: 'act-8',
    type: 'call',
    title: 'Check in with Carl on timeline',
    description: 'Phase 2 rollout. He wanted to start April.',
    contactId: 'cont-12',
    dealId: 'deal-6',
    dueDate: daysAgo(1),
    completed: true,
    createdAt: daysAgo(9),
  },
  {
    id: 'act-9',
    type: 'note',
    title: 'Meridian expansion context',
    description: 'Rachel mentioned 2 new clinics opening in Q2. Good timing for expansion push. Derek confirmed current infra can handle it.',
    contactId: 'cont-1',
    companyId: 'comp-1',
    completed: true,
    createdAt: daysAgo(12),
  },
  {
    id: 'act-10',
    type: 'meeting',
    title: 'QBR with Atlas Pharma',
    description: 'Quarterly review. Greg + Natalie attending. Prepare usage report and roadmap preview.',
    contactId: 'cont-14',
    companyId: 'comp-12',
    dueDate: daysAgo(-7),
    completed: false,
    createdAt: daysAgo(6),
  },
  {
    id: 'act-11',
    type: 'task',
    title: 'Update Vellum proposal with security appendix',
    description: 'Jonathan asked for SOC2 + pentest report references',
    dealId: 'deal-3',
    dueDate: daysAgo(-2),
    completed: false,
    createdAt: daysAgo(3),
  },
  {
    id: 'act-12',
    type: 'email',
    title: 'Sent renewal reminder to Tom',
    contactId: 'cont-8',
    companyId: 'comp-6',
    completed: true,
    createdAt: daysAgo(50),
  },
  {
    id: 'act-13',
    type: 'note',
    title: 'Arclight post-mortem',
    description: 'Lost deal. They built internally. Sandra left. No active contact. Mark as dead unless new champion emerges.',
    companyId: 'comp-7',
    completed: true,
    createdAt: daysAgo(90),
  },
  {
    id: 'act-14',
    type: 'call',
    title: 'Catch up with Zoe re: expansion',
    description: 'Pinecone growing. Might need enterprise tier by summer.',
    contactId: 'cont-5',
    companyId: 'comp-3',
    dueDate: daysAgo(-10),
    completed: false,
    createdAt: daysAgo(7),
  },
  {
    id: 'act-15',
    type: 'task',
    title: 'Research Tidewater competitors',
    description: 'David mentioned they use Guidewire. Check what integrations we need.',
    dealId: 'deal-4',
    dueDate: daysAgo(0),
    completed: false,
    createdAt: daysAgo(6),
  },
];

export const seedCRMSettings: CRMSettings = {
  companyName: 'Orama',
  currency: 'USD',
  isSetupComplete: true,
};
