import type { Product, Customer, Order, Return, StoreSettings } from '../types';

// Helper to generate IDs
const generateId = () => Math.random().toString(36).substring(2, 11);

// Helper to generate dates in the past
const daysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date;
};

export const seedStoreSettings: StoreSettings = {
  store: {
    name: 'Demo Store',
    currency: 'USD',
    taxRate: 0.08,
    isSetupComplete: true,
  },
  shippingZones: [
    {
      id: 'zone-1',
      name: 'Domestic (US)',
      countries: ['United States'],
      rates: [
        { id: 'rate-1', name: 'Standard Shipping', price: 5.99, minOrderValue: 0, maxOrderValue: 49.99 },
        { id: 'rate-2', name: 'Free Shipping', price: 0, minOrderValue: 50 },
        { id: 'rate-3', name: 'Express Shipping', price: 14.99 },
      ],
    },
    {
      id: 'zone-2',
      name: 'International',
      countries: ['Canada', 'United Kingdom', 'Australia', 'Germany', 'France'],
      rates: [
        { id: 'rate-4', name: 'International Standard', price: 19.99 },
        { id: 'rate-5', name: 'International Express', price: 39.99 },
      ],
    },
  ],
  paymentMethods: [
    { id: 'pm-1', name: 'Credit Card', type: 'card', enabled: true },
    { id: 'pm-2', name: 'PayPal', type: 'paypal', enabled: true },
    { id: 'pm-3', name: 'Bank Transfer', type: 'bank_transfer', enabled: false },
  ],
};

export const seedCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'John Smith',
    email: 'john.smith@email.com',
    phone: '+1 555-123-4567',
    totalOrders: 5,
    totalSpent: 459.95,
    createdAt: daysAgo(120),
  },
  {
    id: 'cust-2',
    name: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    phone: '+1 555-234-5678',
    totalOrders: 3,
    totalSpent: 289.97,
    createdAt: daysAgo(90),
  },
  {
    id: 'cust-3',
    name: 'Michael Chen',
    email: 'm.chen@email.com',
    totalOrders: 8,
    totalSpent: 1245.60,
    createdAt: daysAgo(200),
  },
  {
    id: 'cust-4',
    name: 'Emily Davis',
    email: 'emily.d@email.com',
    phone: '+1 555-345-6789',
    totalOrders: 2,
    totalSpent: 159.98,
    createdAt: daysAgo(45),
  },
  {
    id: 'cust-5',
    name: 'Robert Wilson',
    email: 'r.wilson@email.com',
    totalOrders: 1,
    totalSpent: 89.99,
    createdAt: daysAgo(10),
  },
];

export const seedProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Classic Cotton T-Shirt',
    description: 'Comfortable 100% cotton t-shirt perfect for everyday wear. Pre-shrunk fabric with reinforced stitching.',
    price: 29.99,
    sku: 'TSH-001',
    category: 'Clothing',
    tags: ['summer', 'casual', 'cotton', 'bestseller'],
    variants: [
      { id: 'var-1-1', name: 'White / S', sku: 'TSH-001-WH-S', inventory: 25, options: { color: 'White', size: 'S' } },
      { id: 'var-1-2', name: 'White / M', sku: 'TSH-001-WH-M', inventory: 30, options: { color: 'White', size: 'M' } },
      { id: 'var-1-3', name: 'White / L', sku: 'TSH-001-WH-L', inventory: 20, options: { color: 'White', size: 'L' } },
      { id: 'var-1-4', name: 'Black / S', sku: 'TSH-001-BK-S', inventory: 15, options: { color: 'Black', size: 'S' } },
      { id: 'var-1-5', name: 'Black / M', sku: 'TSH-001-BK-M', inventory: 35, options: { color: 'Black', size: 'M' } },
      { id: 'var-1-6', name: 'Black / L', sku: 'TSH-001-BK-L', inventory: 28, options: { color: 'Black', size: 'L' } },
      { id: 'var-1-7', name: 'Navy / M', sku: 'TSH-001-NV-M', inventory: 12, options: { color: 'Navy', size: 'M' } },
      { id: 'var-1-8', name: 'Navy / L', sku: 'TSH-001-NV-L', inventory: 8, options: { color: 'Navy', size: 'L' } },
    ],
    images: [],
    status: 'active',
    createdAt: daysAgo(180),
  },
  {
    id: 'prod-2',
    name: 'Premium Denim Jeans',
    description: 'High-quality denim jeans with stretch comfort. Classic 5-pocket design with modern slim fit.',
    price: 79.99,
    compareAtPrice: 99.99,
    sku: 'JNS-001',
    category: 'Clothing',
    tags: ['denim', 'casual', 'premium'],
    variants: [
      { id: 'var-2-1', name: 'Dark Blue / 30', sku: 'JNS-001-DB-30', inventory: 10, options: { color: 'Dark Blue', size: '30' } },
      { id: 'var-2-2', name: 'Dark Blue / 32', sku: 'JNS-001-DB-32', inventory: 15, options: { color: 'Dark Blue', size: '32' } },
      { id: 'var-2-3', name: 'Dark Blue / 34', sku: 'JNS-001-DB-34', inventory: 12, options: { color: 'Dark Blue', size: '34' } },
      { id: 'var-2-4', name: 'Light Blue / 32', sku: 'JNS-001-LB-32', inventory: 8, options: { color: 'Light Blue', size: '32' } },
      { id: 'var-2-5', name: 'Light Blue / 34', sku: 'JNS-001-LB-34', inventory: 5, options: { color: 'Light Blue', size: '34' } },
    ],
    images: [],
    status: 'active',
    createdAt: daysAgo(150),
  },
  {
    id: 'prod-3',
    name: 'Winter Wool Sweater',
    description: 'Cozy merino wool blend sweater. Perfect for cold weather with classic crew neck design.',
    price: 89.99,
    sku: 'SWT-001',
    category: 'Clothing',
    tags: ['winter', 'wool', 'warm'],
    variants: [
      { id: 'var-3-1', name: 'Charcoal / S', sku: 'SWT-001-CH-S', inventory: 6, options: { color: 'Charcoal', size: 'S' } },
      { id: 'var-3-2', name: 'Charcoal / M', sku: 'SWT-001-CH-M', inventory: 10, options: { color: 'Charcoal', size: 'M' } },
      { id: 'var-3-3', name: 'Charcoal / L', sku: 'SWT-001-CH-L', inventory: 8, options: { color: 'Charcoal', size: 'L' } },
      { id: 'var-3-4', name: 'Burgundy / M', sku: 'SWT-001-BG-M', inventory: 4, options: { color: 'Burgundy', size: 'M' } },
      { id: 'var-3-5', name: 'Burgundy / L', sku: 'SWT-001-BG-L', inventory: 3, options: { color: 'Burgundy', size: 'L' } },
    ],
    images: [],
    status: 'active',
    createdAt: daysAgo(60),
  },
  {
    id: 'prod-4',
    name: 'Canvas Sneakers',
    description: 'Lightweight canvas sneakers with rubber sole. Perfect for casual everyday wear.',
    price: 49.99,
    sku: 'SNK-001',
    category: 'Footwear',
    tags: ['summer', 'casual', 'canvas'],
    variants: [
      { id: 'var-4-1', name: 'White / 8', sku: 'SNK-001-WH-8', inventory: 12, options: { color: 'White', size: '8' } },
      { id: 'var-4-2', name: 'White / 9', sku: 'SNK-001-WH-9', inventory: 15, options: { color: 'White', size: '9' } },
      { id: 'var-4-3', name: 'White / 10', sku: 'SNK-001-WH-10', inventory: 18, options: { color: 'White', size: '10' } },
      { id: 'var-4-4', name: 'Black / 8', sku: 'SNK-001-BK-8', inventory: 10, options: { color: 'Black', size: '8' } },
      { id: 'var-4-5', name: 'Black / 9', sku: 'SNK-001-BK-9', inventory: 14, options: { color: 'Black', size: '9' } },
      { id: 'var-4-6', name: 'Black / 10', sku: 'SNK-001-BK-10', inventory: 16, options: { color: 'Black', size: '10' } },
    ],
    images: [],
    status: 'active',
    createdAt: daysAgo(90),
  },
  {
    id: 'prod-5',
    name: 'Leather Belt',
    description: 'Genuine leather belt with classic buckle. Timeless accessory for any outfit.',
    price: 39.99,
    sku: 'BLT-001',
    category: 'Accessories',
    tags: ['leather', 'classic', 'accessory'],
    variants: [
      { id: 'var-5-1', name: 'Brown / S', sku: 'BLT-001-BR-S', inventory: 20, options: { color: 'Brown', size: 'S' } },
      { id: 'var-5-2', name: 'Brown / M', sku: 'BLT-001-BR-M', inventory: 25, options: { color: 'Brown', size: 'M' } },
      { id: 'var-5-3', name: 'Brown / L', sku: 'BLT-001-BR-L', inventory: 18, options: { color: 'Brown', size: 'L' } },
      { id: 'var-5-4', name: 'Black / S', sku: 'BLT-001-BK-S', inventory: 15, options: { color: 'Black', size: 'S' } },
      { id: 'var-5-5', name: 'Black / M', sku: 'BLT-001-BK-M', inventory: 22, options: { color: 'Black', size: 'M' } },
      { id: 'var-5-6', name: 'Black / L', sku: 'BLT-001-BK-L', inventory: 12, options: { color: 'Black', size: 'L' } },
    ],
    images: [],
    status: 'active',
    createdAt: daysAgo(120),
  },
  {
    id: 'prod-6',
    name: 'Summer Linen Shirt',
    description: 'Breathable linen shirt perfect for warm weather. Relaxed fit with button-down collar.',
    price: 59.99,
    sku: 'LSH-001',
    category: 'Clothing',
    tags: ['summer', 'linen', 'casual'],
    variants: [
      { id: 'var-6-1', name: 'White / S', sku: 'LSH-001-WH-S', inventory: 8, options: { color: 'White', size: 'S' } },
      { id: 'var-6-2', name: 'White / M', sku: 'LSH-001-WH-M', inventory: 12, options: { color: 'White', size: 'M' } },
      { id: 'var-6-3', name: 'White / L', sku: 'LSH-001-WH-L', inventory: 10, options: { color: 'White', size: 'L' } },
      { id: 'var-6-4', name: 'Light Blue / M', sku: 'LSH-001-LB-M', inventory: 6, options: { color: 'Light Blue', size: 'M' } },
      { id: 'var-6-5', name: 'Light Blue / L', sku: 'LSH-001-LB-L', inventory: 4, options: { color: 'Light Blue', size: 'L' } },
    ],
    images: [],
    status: 'active',
    createdAt: daysAgo(30),
  },
  {
    id: 'prod-7',
    name: 'Waterproof Hiking Boots',
    description: 'Durable hiking boots with waterproof membrane. Excellent grip and ankle support.',
    price: 129.99,
    sku: 'HKB-001',
    category: 'Footwear',
    tags: ['outdoor', 'hiking', 'waterproof'],
    variants: [
      { id: 'var-7-1', name: 'Brown / 9', sku: 'HKB-001-BR-9', inventory: 5, options: { color: 'Brown', size: '9' } },
      { id: 'var-7-2', name: 'Brown / 10', sku: 'HKB-001-BR-10', inventory: 7, options: { color: 'Brown', size: '10' } },
      { id: 'var-7-3', name: 'Brown / 11', sku: 'HKB-001-BR-11', inventory: 6, options: { color: 'Brown', size: '11' } },
      { id: 'var-7-4', name: 'Grey / 9', sku: 'HKB-001-GR-9', inventory: 3, options: { color: 'Grey', size: '9' } },
      { id: 'var-7-5', name: 'Grey / 10', sku: 'HKB-001-GR-10', inventory: 4, options: { color: 'Grey', size: '10' } },
    ],
    images: [],
    status: 'active',
    createdAt: daysAgo(75),
  },
  {
    id: 'prod-8',
    name: 'Silk Scarf',
    description: 'Luxurious 100% silk scarf with elegant patterns. Perfect for adding a touch of style.',
    price: 69.99,
    compareAtPrice: 89.99,
    sku: 'SCF-001',
    category: 'Accessories',
    tags: ['silk', 'luxury', 'gift'],
    variants: [
      { id: 'var-8-1', name: 'Floral Blue', sku: 'SCF-001-FB', inventory: 15, options: { pattern: 'Floral Blue' } },
      { id: 'var-8-2', name: 'Classic Red', sku: 'SCF-001-CR', inventory: 12, options: { pattern: 'Classic Red' } },
      { id: 'var-8-3', name: 'Geometric Black', sku: 'SCF-001-GB', inventory: 8, options: { pattern: 'Geometric Black' } },
    ],
    images: [],
    status: 'active',
    createdAt: daysAgo(45),
  },
  {
    id: 'prod-9',
    name: 'Athletic Performance Shorts',
    description: 'Moisture-wicking athletic shorts with built-in liner. Great for running and gym.',
    price: 34.99,
    sku: 'SHR-001',
    category: 'Sportswear',
    tags: ['athletic', 'running', 'gym'],
    variants: [
      { id: 'var-9-1', name: 'Black / S', sku: 'SHR-001-BK-S', inventory: 20, options: { color: 'Black', size: 'S' } },
      { id: 'var-9-2', name: 'Black / M', sku: 'SHR-001-BK-M', inventory: 25, options: { color: 'Black', size: 'M' } },
      { id: 'var-9-3', name: 'Black / L', sku: 'SHR-001-BK-L', inventory: 18, options: { color: 'Black', size: 'L' } },
      { id: 'var-9-4', name: 'Navy / M', sku: 'SHR-001-NV-M', inventory: 15, options: { color: 'Navy', size: 'M' } },
      { id: 'var-9-5', name: 'Navy / L', sku: 'SHR-001-NV-L', inventory: 12, options: { color: 'Navy', size: 'L' } },
    ],
    images: [],
    status: 'active',
    createdAt: daysAgo(20),
  },
  {
    id: 'prod-10',
    name: 'Cashmere Beanie',
    description: 'Soft cashmere blend beanie for ultimate warmth and comfort. One size fits most.',
    price: 44.99,
    sku: 'BNE-001',
    category: 'Accessories',
    tags: ['winter', 'cashmere', 'warm'],
    variants: [
      { id: 'var-10-1', name: 'Black', sku: 'BNE-001-BK', inventory: 30, options: { color: 'Black' } },
      { id: 'var-10-2', name: 'Grey', sku: 'BNE-001-GR', inventory: 25, options: { color: 'Grey' } },
      { id: 'var-10-3', name: 'Burgundy', sku: 'BNE-001-BG', inventory: 18, options: { color: 'Burgundy' } },
      { id: 'var-10-4', name: 'Navy', sku: 'BNE-001-NV', inventory: 22, options: { color: 'Navy' } },
    ],
    images: [],
    status: 'active',
    createdAt: daysAgo(55),
  },
  {
    id: 'prod-11',
    name: 'Organic Cotton Hoodie',
    description: 'Eco-friendly organic cotton hoodie with kangaroo pocket. Soft and sustainable.',
    price: 64.99,
    sku: 'HOD-001',
    category: 'Clothing',
    tags: ['organic', 'sustainable', 'casual'],
    variants: [
      { id: 'var-11-1', name: 'Heather Grey / S', sku: 'HOD-001-HG-S', inventory: 10, options: { color: 'Heather Grey', size: 'S' } },
      { id: 'var-11-2', name: 'Heather Grey / M', sku: 'HOD-001-HG-M', inventory: 14, options: { color: 'Heather Grey', size: 'M' } },
      { id: 'var-11-3', name: 'Heather Grey / L', sku: 'HOD-001-HG-L', inventory: 12, options: { color: 'Heather Grey', size: 'L' } },
      { id: 'var-11-4', name: 'Forest Green / M', sku: 'HOD-001-FG-M', inventory: 8, options: { color: 'Forest Green', size: 'M' } },
      { id: 'var-11-5', name: 'Forest Green / L', sku: 'HOD-001-FG-L', inventory: 6, options: { color: 'Forest Green', size: 'L' } },
    ],
    images: [],
    status: 'active',
    createdAt: daysAgo(40),
  },
  {
    id: 'prod-12',
    name: 'Vintage Sunglasses',
    description: 'Retro-style sunglasses with UV400 protection. Classic design meets modern function.',
    price: 54.99,
    sku: 'SNG-001',
    category: 'Accessories',
    tags: ['summer', 'vintage', 'uv-protection'],
    variants: [
      { id: 'var-12-1', name: 'Tortoise', sku: 'SNG-001-TT', inventory: 20, options: { color: 'Tortoise' } },
      { id: 'var-12-2', name: 'Black', sku: 'SNG-001-BK', inventory: 25, options: { color: 'Black' } },
      { id: 'var-12-3', name: 'Clear', sku: 'SNG-001-CL', inventory: 15, options: { color: 'Clear' } },
    ],
    images: [],
    status: 'active',
    createdAt: daysAgo(35),
  },
  {
    id: 'prod-13',
    name: 'Draft Product - Spring Collection',
    description: 'Upcoming spring collection item. Details to be finalized.',
    price: 0,
    sku: 'DRF-001',
    category: 'Clothing',
    tags: ['spring', 'upcoming'],
    variants: [],
    images: [],
    status: 'draft',
    createdAt: daysAgo(5),
  },
];

export const seedOrders: Order[] = [
  {
    id: 'ord-1',
    orderNumber: '1001',
    customer: seedCustomers[0],
    items: [
      { id: 'oi-1-1', productId: 'prod-1', productName: 'Classic Cotton T-Shirt', variantId: 'var-1-2', variantName: 'White / M', quantity: 2, unitPrice: 29.99, total: 59.98 },
      { id: 'oi-1-2', productId: 'prod-5', productName: 'Leather Belt', variantId: 'var-5-2', variantName: 'Brown / M', quantity: 1, unitPrice: 39.99, total: 39.99 },
    ],
    status: 'delivered',
    subtotal: 99.97,
    shipping: 5.99,
    tax: 8.00,
    total: 113.96,
    shippingAddress: { line1: '123 Main St', city: 'New York', state: 'NY', postalCode: '10001', country: 'United States' },
    trackingNumber: 'TRK123456789',
    createdAt: daysAgo(14),
    updatedAt: daysAgo(10),
  },
  {
    id: 'ord-2',
    orderNumber: '1002',
    customer: seedCustomers[1],
    items: [
      { id: 'oi-2-1', productId: 'prod-2', productName: 'Premium Denim Jeans', variantId: 'var-2-2', variantName: 'Dark Blue / 32', quantity: 1, unitPrice: 79.99, total: 79.99 },
    ],
    status: 'shipped',
    subtotal: 79.99,
    shipping: 0,
    tax: 6.40,
    total: 86.39,
    shippingAddress: { line1: '456 Oak Ave', line2: 'Apt 2B', city: 'Los Angeles', state: 'CA', postalCode: '90001', country: 'United States' },
    trackingNumber: 'TRK987654321',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
  {
    id: 'ord-3',
    orderNumber: '1003',
    customer: seedCustomers[2],
    items: [
      { id: 'oi-3-1', productId: 'prod-3', productName: 'Winter Wool Sweater', variantId: 'var-3-2', variantName: 'Charcoal / M', quantity: 1, unitPrice: 89.99, total: 89.99 },
      { id: 'oi-3-2', productId: 'prod-10', productName: 'Cashmere Beanie', variantId: 'var-10-1', variantName: 'Black', quantity: 1, unitPrice: 44.99, total: 44.99 },
    ],
    status: 'processing',
    subtotal: 134.98,
    shipping: 0,
    tax: 10.80,
    total: 145.78,
    shippingAddress: { line1: '789 Pine Rd', city: 'Chicago', state: 'IL', postalCode: '60601', country: 'United States' },
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: 'ord-4',
    orderNumber: '1004',
    customer: seedCustomers[3],
    items: [
      { id: 'oi-4-1', productId: 'prod-4', productName: 'Canvas Sneakers', variantId: 'var-4-2', variantName: 'White / 9', quantity: 1, unitPrice: 49.99, total: 49.99 },
    ],
    status: 'paid',
    subtotal: 49.99,
    shipping: 5.99,
    tax: 4.00,
    total: 59.98,
    shippingAddress: { line1: '321 Elm St', city: 'Houston', state: 'TX', postalCode: '77001', country: 'United States' },
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'ord-5',
    orderNumber: '1005',
    customer: seedCustomers[4],
    items: [
      { id: 'oi-5-1', productId: 'prod-6', productName: 'Summer Linen Shirt', variantId: 'var-6-2', variantName: 'White / M', quantity: 1, unitPrice: 59.99, total: 59.99 },
      { id: 'oi-5-2', productId: 'prod-9', productName: 'Athletic Performance Shorts', variantId: 'var-9-2', variantName: 'Black / M', quantity: 1, unitPrice: 34.99, total: 34.99 },
    ],
    status: 'pending',
    subtotal: 94.98,
    shipping: 0,
    tax: 7.60,
    total: 102.58,
    shippingAddress: { line1: '555 Maple Dr', city: 'Phoenix', state: 'AZ', postalCode: '85001', country: 'United States' },
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: 'ord-6',
    orderNumber: '1006',
    customer: seedCustomers[0],
    items: [
      { id: 'oi-6-1', productId: 'prod-7', productName: 'Waterproof Hiking Boots', variantId: 'var-7-2', variantName: 'Brown / 10', quantity: 1, unitPrice: 129.99, total: 129.99 },
    ],
    status: 'pending',
    subtotal: 129.99,
    shipping: 0,
    tax: 10.40,
    total: 140.39,
    shippingAddress: { line1: '123 Main St', city: 'New York', state: 'NY', postalCode: '10001', country: 'United States' },
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: 'ord-7',
    orderNumber: '1007',
    customer: seedCustomers[2],
    items: [
      { id: 'oi-7-1', productId: 'prod-8', productName: 'Silk Scarf', variantId: 'var-8-1', variantName: 'Floral Blue', quantity: 2, unitPrice: 69.99, total: 139.98 },
      { id: 'oi-7-2', productId: 'prod-12', productName: 'Vintage Sunglasses', variantId: 'var-12-1', variantName: 'Tortoise', quantity: 1, unitPrice: 54.99, total: 54.99 },
    ],
    status: 'cancelled',
    subtotal: 194.97,
    shipping: 0,
    tax: 15.60,
    total: 210.57,
    shippingAddress: { line1: '789 Pine Rd', city: 'Chicago', state: 'IL', postalCode: '60601', country: 'United States' },
    notes: 'Customer requested cancellation - changed mind',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(6),
  },
  {
    id: 'ord-8',
    orderNumber: '1008',
    customer: seedCustomers[1],
    items: [
      { id: 'oi-8-1', productId: 'prod-11', productName: 'Organic Cotton Hoodie', variantId: 'var-11-2', variantName: 'Heather Grey / M', quantity: 1, unitPrice: 64.99, total: 64.99 },
    ],
    status: 'refunded',
    subtotal: 64.99,
    shipping: 0,
    tax: 5.20,
    total: 70.19,
    shippingAddress: { line1: '456 Oak Ave', line2: 'Apt 2B', city: 'Los Angeles', state: 'CA', postalCode: '90001', country: 'United States' },
    notes: 'Refunded due to product defect',
    createdAt: daysAgo(20),
    updatedAt: daysAgo(15),
  },
];

export const seedReturns: Return[] = [
  {
    id: 'ret-1',
    orderId: 'ord-8',
    orderNumber: '1008',
    items: [
      { orderItemId: 'oi-8-1', productName: 'Organic Cotton Hoodie', variantName: 'Heather Grey / M', quantity: 1, reason: 'Product defect - stitching came undone' },
    ],
    status: 'refunded',
    refundAmount: 70.19,
    createdAt: daysAgo(16),
  },
];

// Helper to get total inventory for a product
export const getProductInventory = (product: Product): number => {
  return product.variants.reduce((sum, v) => sum + v.inventory, 0);
};

// Helper to get low stock products (less than 10 total units)
export const getLowStockProducts = (products: Product[]): Product[] => {
  return products.filter(p => p.status === 'active' && getProductInventory(p) < 10);
};

// Helper to generate a new order number
export const generateOrderNumber = (orders: Order[]): string => {
  const maxNumber = orders.reduce((max, o) => {
    const num = parseInt(o.orderNumber, 10);
    return num > max ? num : max;
  }, 1000);
  return (maxNumber + 1).toString();
};
